

---
apiVersion: v1
kind: Service
metadata:
  name: zinc-server-svc
  namespace: user-system-{{ .Values.bfl.username }}
spec:
  type: ClusterIP
  selector:
    app: systemserver
  ports:
    - protocol: TCP
      name: zinc
      port: 80
      targetPort: 8080