

{{- $redis_secret := (lookup "v1" "Secret" .Release.Namespace "redis-cluster-admin") -}}
{{- $password := "" -}}
{{ if $redis_secret -}}
{{ $password = (index $redis_secret "data" "password") }}
{{ else -}}
{{ $password = randAlphaNum 16 | b64enc }}
{{- end -}}
{{ $redis_rootpath := "/terminus/userdata/dbdata" }}

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-cluster-admin
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ $password }}

---
apiVersion: redis.kun/v1alpha1
kind: DistributedRedisCluster
metadata:
  name: redis-cluster
  namespace: {{ .Release.Namespace }}
  annotations:
    redis.kun/scope: cluster-scoped
spec:
  # Add fields here
  masterSize: 1
  clusterReplicas: 1
  image: redis:6.2.13-alpine3.18
  imagePullPolicy: IfNotPresent
  config:
    activerehashing: "yes"
    appendfsync: everysec
    appendonly: "yes"
  storage:
    type: hostPath
    hostPath:
      type: DirectoryOrCreate
      path: {{ $redis_rootpath }}/redisdata
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 20m
      memory: 100Mi  
  passwordSecret:
    name: redis-cluster-admin

---
apiVersion: v1
data:
  predixy.conf: |
    ################################### GENERAL ####################################
    Name PredixyServer
    Bind 0.0.0.0:6379
    WorkerThreads 4
    ClientTimeout 300
    LogVerbSample 0
    LogDebugSample 1
    LogInfoSample 10000
    LogNoticeSample 1
    LogWarnSample 1
    LogErrorSample 1
    ################################### AUTHORITY ##################################
    ################################### SERVERS ####################################
    ClusterServerPool {
      Password {{ $password | b64dec }}
      MasterReadPriority 60
      StaticSlaveReadPriority 50
      DynamicSlaveReadPriority 50
      RefreshInterval 10
      ServerTimeout 10
      ServerFailureLimit 10
      ServerRetryTimeout 1
      KeepAlive 120
      Servers {
          + drc-redis-cluster-0-0.redis-cluster-0.os-system:6379
          + drc-redis-cluster-0-1.redis-cluster-0.os-system:6379
      }
    }
kind: ConfigMap
metadata:
  name: predixy-configs
  namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-proxy
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: proxy
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    name: redis-cluster-proxy

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cluster-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    applications.app.bytetrade.io/author: bytetrade.io
  annotations:
    applications.app.bytetrade.io/version: '0.0.1'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-cluster-proxy
  template:
    metadata:
      labels:
        name: redis-cluster-proxy
    spec:
      containers:
      - name: proxy
        image: beclab/predixy-alpine:0.1.2
        imagePullPolicy: IfNotPresent
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        command:
        - /predixy
        - /conf/predixy.conf
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: config
          mountPath: /conf

      volumes:
      - name: config
        configMap:
          name: predixy-configs
          defaultMode: 438
