

{{ $search_rootpath := "/terminus/rootfs/search" }}
{{- $zinc_secret := (lookup "v1" "Secret" .Release.Namespace "zinc-server-admin") -}}
{{- $password := "" -}}
{{ if $zinc_secret -}}
{{ $password = (index $zinc_secret "data" "password") }}
{{ else -}}
{{ $password = randAlphaNum 16 | b64enc }}
{{- end -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: zinc-server-admin
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ $password }}

---
apiVersion: v1
kind: Service
metadata:
  name: zinc-server-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: zinc-server
  ports:
  - name: http
    port: 80
    targetPort: 4080

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zinc-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: zinc-server
    applications.app.bytetrade.io/author: bytetrade.io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zinc-server
  serviceName: "zinc-server"
  template:
    metadata:
      labels:
        app: zinc-server
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: zinc-server
        image: beclab/zincsearch:v0.4.7
        env:
          - name: ZINC_FIRST_ADMIN_USER
            value: admin
          - name: ZINC_FIRST_ADMIN_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: zinc-server-admin
                key: password
          - name: ZINC_DATA_PATH
            value: /data
        # command: ["/bin/bash", "-c", "while true; do sleep 1; done"]
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 4080
            name: http
        volumeMounts:
        - name: index-data
          mountPath: /data
      volumes:
      - name: index-data
        hostPath:
          type: DirectoryOrCreate
          path: {{ $search_rootpath }}/zinc-data

