apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: orionx-client-update
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: orionx-client-update
  template:
    metadata:
      labels:
        app: orionx-client-update
    spec:
      containers:
      - name: client-update
        image: eball/orion-client-update-multi-arch:3.4.2-cuda-4.2.1-opengl-1.4.0-neuware-2.4.1-20231108
        imagePullPolicy: IfNotPresent 
        env:
        - name: ORION_CONTROLLER
          value: {{ .Values.gpu.server }}
        - name: ORION_BIND_ADDR
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: ORION_ARCH_LIST
          value: cuda
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: orionx-runtime-root
          mountPath: /opt/orion/orion_runtime/
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: orionx-runtime-root
        hostPath:
          path: /opt/orion/orion_runtime/
          type: DirectoryOrCreate
