

# Default values for ks-core.

replicaCount: 1

image:
  # Overrides the image tag whose default is the chart appVersion.
  ks_console_repo: "kubesphere/ks-console"
  ks_console_tag: ""
  pullPolicy: IfNotPresent


# Kubernetes Version shows in KubeSphere console
kube_version: "v1.19.4"

env: []

tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 60
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 60


console:
  type: ClusterIP
  defaultClusterName: "default"
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 100Mi

bfl:
  username: test
